import React from "react";
import "./AddStudent.css";

<<<<<<< HEAD
=======
import API from "../../services/api";


>>>>>>> d2a95a7ef60f732a12049080be26ed7f5cdfc51b
class AddStudent extends React.Component {
  state = {
    fName: "",
    midInit: "",
    lName: "",
    stName: "",
    stNo: "",
    apartNo: "",
    city: "",
    state: "",
    ZIP: "",
    phoneNo: "",
    email: "",
    courseCode: "",
  };

  inputUpdate = (event) => {
    let key = event.target.name;
    let val = event.target.value;
    this.setState({ [key]: val });
    // this.setState({fName: event.target.value});
    // this.setState({midInit: event.target.value});
    // this.setState({lName: event.target.value});
  };

  render() {
    return (
      <div className="st_form">
        <h1> Student Management </h1>

        <div className="form_area">
          <div className="center_align">
            {/* <label className="sameLineL" for= "stNo" > Student Number : </label>
               <input className="sameLineI" type="text" name="stNo" id="stNo" value={this.state.stNo} onChange={(ev) => this.setState({ stNo: ev.target.value })} /> */}
            <p className="stId"> Student ID - autoGenerated 123 </p>
          </div>

          <form className="ui form">
            {/* <p className="fullName" > (TESTING - {this.state.fName} {" "} {this.state.midInit}{" "} {this.state.lName} ) </p>  */}
            <div className="center_align">
              
              <div className="three fields">
                <div class="field">
                  <label> First Name:</label>
                  <input
                    type="text"
                    value={this.state.fName}
                    onChange={(ev) =>
                      this.setState({ fName: ev.target.value.toUpperCase() })
                    }
                    name="fName"
                    placeholder="USE CAPITAL LETTERS"
                  />
                  {/* <input type="text" id="fname" name="fname" onClick={(ev) => this.setState({ fName: ev.target.value.toUpperCase() }) }/> */}
                </div>

                <div class="field">
                  <label> Middle Initials:</label>
                  <input type = "text" name = "midInit" value = {this.state.midInit} onChange = {(ev) =>this.setState({ midInit: ev.target.value.toUpperCase() })}/>
                </div>
                <div class="field">
                  <label> Last Name:</label>
                  <input type = "text" name = "lName" onClick = {(ev) => this.setState({ lName: ev.target.value.toUpperCase() }) }/>
                </div>
              </div>
              
              <div className="two fields">
                <div className="field" >
                  <label for="gender"> Gender :</label>
                  <select id="gender" name="gender" onChange={this.inputUpdate} >
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                    <option value="other">Other</option>
                  </select>
                </div>

                <div class="field" >
                  <label for="profession"> Profession :</label>
                  <select id="profession" name="profession" onChange={this.inputUpdate}> 
                    <option value="student">Student </option>
                    <option value="employee">Employee </option>
                    <option value="Employer">Employer </option>
                    <option value="lorem">Lorem ipsum </option>
                  </select>
                </div>
              </div> 
              
              <div className="two fields">
                <div className="field" >
                  <label> Street Name & Number :</label>
                  <input
                    type="text"
                    name="stName"
                    onChange={this.inputUpdate}
                  />
                </div>

                <div class="field" >
                  <label> Apartment # :</label>
                  <input
                    type="text"
                    name="apartNo"
                    onChange={this.inputUpdate}
                  />
                </div>
              </div>

            </div>

            <div className="center_align">

              <div className="two fields">
                <div className="field">
                  <label> City:</label>
                  <input type="text" name="city" onChange={this.inputUpdate} />
                </div>

                <div className="field">
                  <label> State:</label>
                  <input type="text" name="state" onChange={this.inputUpdate} />
                </div>
              </div>

              <div className="two fields">    
                <div className="field">
                  <label> Country:</label>
                  <input type="text" name="ZIP" onChange={this.inputUpdate} />
                </div>

                <div className="field">
                  <label> Zip Code: </label>
                  <input type="text" name="ZIP" onChange={this.inputUpdate} />
                </div>
              </div> 
              
              <div className="two fields"> 

                <div className="field">
                  <label> Email Address:</label>
                  <input type="email" name="email" onChange={this.inputUpdate} />
                </div>
                <div className="field">
                  <label> Mobile Number:</label>
                  <input type="text" name="phoneNo" onChange={this.inputUpdate} />
                </div>
              </div>  
              
              <div className="two fields">
                <div className="field">
                  <label> Emergency Contact:</label>
                  <input type="text" name="phoneNo" onChange={this.inputUpdate} />
                </div>                
                <div className="field">
                 <label> Relationship:</label>
                  <input type="text" name="relationship" onChange={this.inputUpdate} />
                </div>
              </div>
              
              <div className="field">
                <label>Course Code:</label>
                <input
                  type="text"
                  name="courseCode"
                  onChange={this.inputUpdate}
                />
              </div>

              <div className="field">
                <button className="ui fluid teal large button" style={{ width: "20%" }} >
                  Submit
                </button>

                <button className="ui fluid  large button" style={{ width: "10%" }} >
                  Close
                </button>
              </div>

            </div>
          </form>
        </div>
      </div>
    );
  }
}
export default AddStudent;
