import React  from "react";
import "./AddNewStud.css";
import AddStudent,{p}  from "../AddStudent/AddStudent";

class AddNewStud extends React.Component {
  state = {
    Name: "",
    address:"",    
    stNo: "",
    bDay:"",
    phoneNo: "",
    email: ""    
  };

  inputUpdate = (event) => {
    let key = event.target.name;
    let val = event.target.value;
    this.setState({ [key]: val });   
  };

  render() {
    return (
      <div className="st_form">
        <h1> Add Student  </h1>

        <div className="form_area">
          <div className="center_align">
            <p className="stId"> Student ID - autoGenerated 123 </p>
          </div>

          <form className="ui form">
            <div className="center_align">
              
              <div className="three fields">
                <div class="field">
                  <label> First Name:</label>
                  <input type = "text" name="fName" value={this.state.fName} onChange={(ev) => this.setState({ fName: ev.target.value.toUpperCase() })} placeholder="USE CAPITAL LETTERS"/>
                </div>
                <div class="field">
                  <label> Middle Initials:</label>
                  <input type = "text" name = "midInit" value = {this.state.midInit} onChange = {(ev) =>this.setState({ midInit: ev.target.value.toUpperCase() })}/>
                </div>
                <div class="field">
                  <label> Last Name:</label>
                  <input type = "text" name = "lName" value = {this.state.midInit} onChange = {(ev) => this.setState({ lName: ev.target.value.toUpperCase() }) }/>
                </div>
              </div>
              
              <div className="two fields">
                <div className="field" >
                  <label for="gender"> Gender :</label>
                  <select id="gender" name="gender" onChange={this.inputUpdate} >
                    <option value="male">Male</option>
                    <option value="female">Female</option>
                    <option value="other">Other</option>
                  </select>
                </div> 
                                
                <div className="field"> 
                  <label> Date of Birth:</label>
                  <input type="date" name="dob" onChange={this.inputUpdate} placeholder="DD/ MM/ YYYY"/>
                </div>               
              </div> 
              
              <div className="two fields">
                <div className="field" >
                  <label> Street Name & Number :</label>
                  <input
                    type="text"
                    name="stName"
                    onChange={this.inputUpdate}
                  />
                </div>

                <div class="field" >
                  <label> Apartment # :</label>
                  <input
                    type="text"
                    name="apartNo"
                    onChange={this.inputUpdate}
                  />
                </div>
              </div>

            </div>

            <div className="center_align">

              <div className="two fields">
                <div className="field">
                  <label> City:</label>
                  <input type="text" name="city" onChange={this.inputUpdate} />
                </div>

                <div className="field">
                  <label> State:</label>
                  <input type="text" name="state" onChange={this.inputUpdate} />
                </div>
              </div>

              <div className="two fields">    
                <div className="field">
                  <label> Country:</label>
                  <input type="text" name="ZIP" onChange={this.inputUpdate} />
                </div>

                <div className="field">
                  <label> Zip Code: </label>
                  <input type="text" name="ZIP" onChange={this.inputUpdate} />
                </div>
              </div> 
              
              <div className="two fields"> 

                <div className="field">
                  <label> Email Address:</label>
                  <input type="email" name="email" onChange={this.inputUpdate} />
                </div>
                <div className="field">
                  <label> Mobile Number:</label>
                  <input type="text" name="phoneNo" onChange={this.inputUpdate} />
                </div>
              </div>  
              
              <div className="two fields">
                <div className="field">
                  <label> Emergency Contact:</label>
                  <input type="text" name="phoneNo" onChange={this.inputUpdate} />
                </div>                
                <div className="field">
                 <label> Relationship:</label>
                  <input type="text" name="relationship" onChange={this.inputUpdate} />
                </div>
              </div>
              
              <div className="field">
                <label>Course Code:</label>
                <input
                  type="text"
                  name="courseCode"
                  onChange={this.inputUpdate}
                />
              </div>
              

              <div className="field">
                <button className="ui fluid teal large button" style={{ width: "20%" }} >
                  Add Student
                </button>

                <button className="ui fluid  large button" style={{ width: "10%" }} >
                  Close
                </button>
              </div>

            </div>
          </form>
        </div>
      </div>
    );
  }
}
export default AddNewStud;
